---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: regcred
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: dev
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
