---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: dev
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: hashicorp/http-echo
          args:
            - "-listen=:8080"
            - '-text="This is Home Page"'
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: dev
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080		# Port exposed within the cluster
      targetPort: 8080	# Port on the pods
  selector:
    app: hello-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - demo.example.com
      secretName: ingress-cert
  rules:
  - host: demo.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hello-world-service
              port:
                number: 8080