apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-application-canary
  namespace: prd
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  rules:
    - host: demo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app-service-canary
                port:
                  number: 8080