---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: dev
spec:
  containers:
    - name: my-app
      image: nginx
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: my-volume
          mountPath: /app
  volumes:
    - name: my-volume
      hostPath:
        path: /data
        type: Directory
