apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-acc-role
  namespace: dev
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-acc-role-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-acc-role
subjects:
  - namespace: dev
    kind: ServiceAccount
    name: service-acc
