---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: hello-world
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world-rc
  namespace: dev
  labels:
    name: hello-world
spec:
  replicas: 2
  selector:
    name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - name: hello-world
          image: ubuntuk8s/helloworld:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 80		# Port exposed within the cluster
  selector:
    name: hello-world
