---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: hello-world
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-world-replicaset
  namespace: dev
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: ubuntuk8s/helloworld:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: dev
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80		# Port exposed within the cluster
      targetPort: 80	# Port on the pods
      nodePort: 30000	# Port accessible externally on each node
  selector:
    app: hello-world
